### ISSUE TITLE
Update to latest 1.8?

### ISSUE THREAD

**Issue by spotlightishere** [mehrdada/google-appengine-go-sdk-linux-arm#1]
Hello!

I recently obtained access to an arm64 server. I set up Jenkins and wanted to use `gcloud app deploy` with my Go application. However, the component `app-engine-go` isn't available for arm natively. This repo seems to provide that, but its version is extremely outdated (`go1.0.3 (appengine-1.7.7)`) compared to the latest version (`1.8.5 (appengine-1.9.65)`).

Is there a way I could update this myself without being a Google employee, or if not could you please update it?

Thanks!

**Comment by mehrdada** [comment]
@spotlightishere Thanks for your interest in this project. This repo is many years old and long precedes my time at Google and done independently to build AppEngine apps with Go on Linux installed on a Samsung ARM Chromebook, so it is definitely not related to Google at all. It's not ARM64 ready and it's pretty old version of the SDK that I pieced together and built some of the components from source again on the ARM platform. I haven't personally looked at this or the changes in AppEngine SDK since then, so I don't think this would be useful to you. (I think the gcloud tool itself is much newer than the SDK that this was built on.)

**Comment by spotlightishere** [comment]
I'll have to figure out another way to go about this. Thank you for the response!
